
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action newAction;
	
	private global::Gtk.HPaned hpaned1;
	
	private global::Gtk.VPaned vpaned1;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TreeView treeview2;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	
	private global::Gtk.TreeView treeview3;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView textviewChat;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Entry entryChat;
	
	private global::Gtk.Button buttonSend;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.newAction = new global::Gtk.Action ("newAction", null, null, "gtk-new");
		w1.Add (this.newAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.AllowShrink = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 182;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 236;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		this.GtkScrolledWindow1.BorderWidth = ((uint)(3));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.treeview2 = new global::Gtk.TreeView ();
		this.treeview2.CanFocus = true;
		this.treeview2.Name = "treeview2";
		this.GtkScrolledWindow1.Add (this.treeview2);
		this.vpaned1.Add (this.GtkScrolledWindow1);
		global::Gtk.Paned.PanedChild w3 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.GtkScrolledWindow1]));
		w3.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		this.GtkScrolledWindow2.BorderWidth = ((uint)(3));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.treeview3 = new global::Gtk.TreeView ();
		this.treeview3.CanFocus = true;
		this.treeview3.Name = "treeview3";
		this.GtkScrolledWindow2.Add (this.treeview3);
		this.vpaned1.Add (this.GtkScrolledWindow2);
		this.hpaned1.Add (this.vpaned1);
		global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vpaned1]));
		w6.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		this.GtkScrolledWindow.BorderWidth = ((uint)(3));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textviewChat = new global::Gtk.TextView ();
		this.textviewChat.CanFocus = true;
		this.textviewChat.Name = "textviewChat";
		this.textviewChat.Editable = false;
		this.GtkScrolledWindow.Add (this.textviewChat);
		this.vbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
		w8.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entryChat = new global::Gtk.Entry ();
		this.entryChat.CanFocus = true;
		this.entryChat.Name = "entryChat";
		this.entryChat.IsEditable = true;
		this.entryChat.InvisibleChar = '•';
		this.hbox1.Add (this.entryChat);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entryChat]));
		w9.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonSend = new global::Gtk.Button ();
		this.buttonSend.CanDefault = true;
		this.buttonSend.CanFocus = true;
		this.buttonSend.Name = "buttonSend";
		this.buttonSend.UseUnderline = true;
		this.buttonSend.BorderWidth = ((uint)(3));
		this.buttonSend.Label = global::Mono.Unix.Catalog.GetString ("Send");
		this.hbox1.Add (this.buttonSend);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonSend]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox2.Add (this.hbox1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.hpaned1.Add (this.vbox2);
		this.Add (this.hpaned1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 693;
		this.DefaultHeight = 598;
		this.buttonSend.HasDefault = true;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
