
// This file has been generated by the GUI designer. Do not modify.
namespace RiftChat
{
	public partial class ContactWidget
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label labelName;
		
		private global::Gtk.ToggleButton togglebuttonOffline;
		
		private global::Gtk.ToggleButton togglebuttonMobile;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treeviewContacts;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RiftChat.ContactWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "RiftChat.ContactWidget";
			// Container child RiftChat.ContactWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.labelName = new global::Gtk.Label ();
			this.labelName.Name = "labelName";
			this.labelName.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox1.Add (this.labelName);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.labelName]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.togglebuttonOffline = new global::Gtk.ToggleButton ();
			this.togglebuttonOffline.CanFocus = true;
			this.togglebuttonOffline.Name = "togglebuttonOffline";
			this.togglebuttonOffline.UseUnderline = true;
			this.togglebuttonOffline.Label = global::Mono.Unix.Catalog.GetString ("Offline");
			global::Gtk.Image w2 = new global::Gtk.Image ();
			w2.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-disconnect", global::Gtk.IconSize.Menu);
			this.togglebuttonOffline.Image = w2;
			this.hbox1.Add (this.togglebuttonOffline);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.togglebuttonOffline]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.togglebuttonMobile = new global::Gtk.ToggleButton ();
			this.togglebuttonMobile.CanFocus = true;
			this.togglebuttonMobile.Name = "togglebuttonMobile";
			this.togglebuttonMobile.UseUnderline = true;
			this.togglebuttonMobile.Active = true;
			this.togglebuttonMobile.Label = global::Mono.Unix.Catalog.GetString ("Mobile");
			global::Gtk.Image w4 = new global::Gtk.Image ();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_cell-phone", global::Gtk.IconSize.Menu);
			this.togglebuttonMobile.Image = w4;
			this.hbox1.Add (this.togglebuttonMobile);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.togglebuttonMobile]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeviewContacts = new global::Gtk.TreeView ();
			this.treeviewContacts.CanFocus = true;
			this.treeviewContacts.Name = "treeviewContacts";
			this.GtkScrolledWindow.Add (this.treeviewContacts);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w8.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
